### ISSUE TITLE
set value of fields programmatically

### ISSUE THREAD

**Issue by tkart38** [Remo/attribute-free-form#2]
hi 
thanks for your work.
how can i set the value of fields programmatically ?
if i've multiple fileds?
thanks

**Comment by Remo** [comment]
I think that's currently not possible because I didn't implement `saveValue`

**Comment by Remo** [comment]
can you please check if my last comment works for you? There's also an example here https://github.com/Remo/attribute-free-form#example-4---save-fields-programmatically

**Comment by tkart38** [comment]
hi this work fine!

A question if i want to add programmatically an attribute with multiple txt fields (like address type)?

i'm tryng using CollectionAttributeKey::add() but with attribute free form is not possible because must pass the edit form and view.

would be awsome use attribute free form for create the attribute type and programmaticaly use the type created for add multiple attribute.
